apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-runtime-image
spec:
  params:
    - name: TLSVERIFY
      type: string
      default: 'false'
    - name: STORAGE_DRIVER
      type: string
  resources:
    inputs:
      - name: intermediate-image
        type: image
    outputs:
      - name: runtime-image
        type: image
  steps:
    - name: gen-binary-extraction-dockerfile
      command:
        - /bin/sh
        - '-c'
      args:
        - |-
          echo "FROM $(resources.inputs.intermediate-image.url) as intermediate-image" > ext-dockerfile.gen
          echo "FROM image-registry.openshift-image-registry.svc:5000/hello-world/jboss-eap74-openjdk8-runtime-openshift as runtime-image" >> ext-dockerfile.gen
          echo "COPY --from=intermediate-image /deployments/liberty-rest-app.war /config/apps/liberty-rest-app.war" >> ext-dockerfile.gen
          echo "COPY --from=intermediate-image /deployments/server.xml /config/server.xml" >> ext-dockerfile.gen
          echo "------------------------------"
          cat ext-dockerfile.gen
          echo "------------------------------"
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
      volumeMounts:
        - name: envparams
          mountPath: /env-params
      workingDir: /env-params
    - name: create-runtime-image
      command:
        - buildah
        - bud
        - '--tls-verify=$(params.TLSVERIFY)'
        - '--storage-driver=$(params.STORAGE_DRIVER)'
        - '--layers'
        - '-f'
        - /env-params/ext-dockerfile.gen
        - '-t'
        - $(resources.outputs.runtime-image.url)
        - .
      image: registry.redhat.io/rhel8/buildah
      resources: {}
      volumeMounts:
        - name: pipeline-cache
          mountPath: /var/lib/containers
        - name: envparams
          mountPath: /env-params
      workingDir: /var/lib/containers
#    - name: view-images
#      command:
#        - buildah
#        - images
#        - '--storage-driver=$(params.STORAGE_DRIVER)'
#      image: registry.redhat.io/rhel8/buildah
#      resources: {}
#      volumeMounts:
#        - name: pipeline-cache
#          mountPath: /var/lib/containers
    - name: push-runtime-image-to-openshift
      command:
        - buildah
        - push
        - '--storage-driver=$(params.STORAGE_DRIVER)'
        - '--tls-verify=$(params.TLSVERIFY)'
        - $(resources.outputs.runtime-image.url)
        - 'docker://$(resources.outputs.runtime-image.url)'
      image: registry.redhat.io/rhel8/buildah
      resources: {}
      volumeMounts:
        - name: pipeline-cache
          mountPath: /var/lib/containers
  volumes:
    - emptyDir: {}
      name: envparams
    - emptyDir: {}
      name: gen-source
    - name: pipeline-cache
      persistentVolumeClaim:
        claimName: lis-pipeline-cache-pvc