
# https://redhat-scholars.github.io/tekton-tutorial/tekton-tutorial/workspaces.html
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: lis-pipeline-run-
  labels:
    app: poc
spec:
  pipelineRef:
    name: lis-pipeline
  resources:
    - name: hello-world-source
      resourceRef:
        name: hello-world-source
    - name: intermediate-image
      resourceRef:
        name: intermediate
    - name: runtime-image
      resourceRef:
        name: hello-world-app
  workspaces:
    - name: pipeline-cache # this workspace name must be declared in the Pipeline
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 20Gi
