apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-test-pipeline
  namespace: hello-world
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/lbamford/jboss-eap-quickstarts.git
        - name: revision
          value: 7.4.x
        - name: deleteExisting
          value: "true"
    - name: mvn-package
      taskRef:
        name: maven
      runAfter:
        - fetch-repo
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
      params:
        - name: CONTEXT_DIR
          value: helloworld-html5
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - package
    - name: s2i
      taskRef:
        name: s2i
      runAfter:
        - mvn-package
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: BUILDER_IMAGE
          value: docker.io/spidee/eap74-openjdk11-runtime-openshift-rhel8
        - name: PATH_CONTEXT
          value: helloworld-html5
        - name: TLSVERIFY
          value: "false"
        - name: LOGLEVEL
          value: "10"
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)
  
