
# https://redhat-scholars.github.io/tekton-tutorial/tekton-tutorial/workspaces.html
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: lis-pipeline-run-
  namespace: hello-world
spec:
  pipelineRef:
    name: lis-pipeline
  resources:
    - name: hello-world-source
      resourceRef:
        name: hello-world-source
    - name: intermediate-image
      resourceRef:
        name: intermediate
    - name: runtime-image
      resourceRef:
        name: hello-world-app
  #workspaces:
   # - name: maven-settings-xml
   #   configMap:
   #     name: hello-world-settings-xml
   # - name: pipeline-cache
   #   persistentVolumeClaim:
   #     claimName: lis-pipeline-cache-pvc

