apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lis-pipeline
  namespace: hello-world
spec:
  resources:
  - name: hello-world-source
    type: git
  workspaces:
  - name: pipeline-cache
  - name: maven-settings-xml
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: pipeline-cache
    params:
    - name: url
      value: https://github.com/lbamford/jboss-eap-quickstarts.git
    - name: revision
      value: 7.4.x
    - name: deleteExisting
      value: "true"
  - name: mvn-package
    taskRef:
      name: maven
    runAfter: 
    - fetch-repo
    workspaces:
    - name: maven-settings
      workspace: maven-settings-xml
    - name: source
      workspace: pipeline-cache
    params:
    - name: CONTEXT_DIR
      value: helloworld-html5
    - name: GOALS
      value:
      - -DskipTests
      - clean
      - package
  
    #- name: s2i
    #  taskRef:
    #    name: s2i
    #  runAfter:
    #    - mvn-package
    #  workspaces:
    #    - name: source
    #      workspace: shared-workspace
    #  params:
    #    - name: BUILDER_IMAGE
    #      value: docker.io/spidee/eap74-openjdk11-runtime-openshift-rhel8
    #    - name: PATH_CONTEXT
    #      value: helloworld-html5
    #    - name: TLSVERIFY
    #      value: "false"
    #    - name: LOGLEVEL
    #      value: "10"
    #    - name: IMAGE
    #      value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)
  
