apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  labels:
    app: frontend
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: 'https://github.com/spiro-redhat/gitops.git'
    path: apps/hello-world
    revision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: '30'
        factor: 2
        maxDuration: '5'
      limit: 6
  project: default
