apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-runner
spec:
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  steps: 
    - name: run-sh
      command:
        - /bin/sh
        - '-c'
      args:
        - |-
          ls  /workspace/maven-settings
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
  workspaces:
    - name: pipeline-cache
      mountPath: /workspace